/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef HelloWorldService_H
#define HelloWorldService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "test_types.h"

namespace test { namespace thrift {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class HelloWorldServiceIf {
 public:
  virtual ~HelloWorldServiceIf() {}
  virtual void sayHello(std::string& _return, const std::string& username) = 0;
};

class HelloWorldServiceIfFactory {
 public:
  typedef HelloWorldServiceIf Handler;

  virtual ~HelloWorldServiceIfFactory() {}

  virtual HelloWorldServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(HelloWorldServiceIf* /* handler */) = 0;
};

class HelloWorldServiceIfSingletonFactory : virtual public HelloWorldServiceIfFactory {
 public:
  HelloWorldServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<HelloWorldServiceIf>& iface) : iface_(iface) {}
  virtual ~HelloWorldServiceIfSingletonFactory() {}

  virtual HelloWorldServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(HelloWorldServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<HelloWorldServiceIf> iface_;
};

class HelloWorldServiceNull : virtual public HelloWorldServiceIf {
 public:
  virtual ~HelloWorldServiceNull() {}
  void sayHello(std::string& /* _return */, const std::string& /* username */) {
    return;
  }
};

typedef struct _HelloWorldService_sayHello_args__isset {
  _HelloWorldService_sayHello_args__isset() : username(false) {}
  bool username :1;
} _HelloWorldService_sayHello_args__isset;

class HelloWorldService_sayHello_args {
 public:

  HelloWorldService_sayHello_args(const HelloWorldService_sayHello_args&);
  HelloWorldService_sayHello_args& operator=(const HelloWorldService_sayHello_args&);
  HelloWorldService_sayHello_args() : username() {
  }

  virtual ~HelloWorldService_sayHello_args() throw();
  std::string username;

  _HelloWorldService_sayHello_args__isset __isset;

  void __set_username(const std::string& val);

  bool operator == (const HelloWorldService_sayHello_args & rhs) const
  {
    if (!(username == rhs.username))
      return false;
    return true;
  }
  bool operator != (const HelloWorldService_sayHello_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloWorldService_sayHello_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class HelloWorldService_sayHello_pargs {
 public:


  virtual ~HelloWorldService_sayHello_pargs() throw();
  const std::string* username;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _HelloWorldService_sayHello_result__isset {
  _HelloWorldService_sayHello_result__isset() : success(false) {}
  bool success :1;
} _HelloWorldService_sayHello_result__isset;

class HelloWorldService_sayHello_result {
 public:

  HelloWorldService_sayHello_result(const HelloWorldService_sayHello_result&);
  HelloWorldService_sayHello_result& operator=(const HelloWorldService_sayHello_result&);
  HelloWorldService_sayHello_result() : success() {
  }

  virtual ~HelloWorldService_sayHello_result() throw();
  std::string success;

  _HelloWorldService_sayHello_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const HelloWorldService_sayHello_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const HelloWorldService_sayHello_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloWorldService_sayHello_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _HelloWorldService_sayHello_presult__isset {
  _HelloWorldService_sayHello_presult__isset() : success(false) {}
  bool success :1;
} _HelloWorldService_sayHello_presult__isset;

class HelloWorldService_sayHello_presult {
 public:


  virtual ~HelloWorldService_sayHello_presult() throw();
  std::string* success;

  _HelloWorldService_sayHello_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class HelloWorldServiceClient : virtual public HelloWorldServiceIf {
 public:
  HelloWorldServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  HelloWorldServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void sayHello(std::string& _return, const std::string& username);
  void send_sayHello(const std::string& username);
  void recv_sayHello(std::string& _return);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class HelloWorldServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<HelloWorldServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (HelloWorldServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_sayHello(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  HelloWorldServiceProcessor(::apache::thrift::stdcxx::shared_ptr<HelloWorldServiceIf> iface) :
    iface_(iface) {
    processMap_["sayHello"] = &HelloWorldServiceProcessor::process_sayHello;
  }

  virtual ~HelloWorldServiceProcessor() {}
};

class HelloWorldServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  HelloWorldServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< HelloWorldServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< HelloWorldServiceIfFactory > handlerFactory_;
};

class HelloWorldServiceMultiface : virtual public HelloWorldServiceIf {
 public:
  HelloWorldServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<HelloWorldServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~HelloWorldServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<HelloWorldServiceIf> > ifaces_;
  HelloWorldServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<HelloWorldServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void sayHello(std::string& _return, const std::string& username) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->sayHello(_return, username);
    }
    ifaces_[i]->sayHello(_return, username);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class HelloWorldServiceConcurrentClient : virtual public HelloWorldServiceIf {
 public:
  HelloWorldServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  HelloWorldServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void sayHello(std::string& _return, const std::string& username);
  int32_t send_sayHello(const std::string& username);
  void recv_sayHello(std::string& _return, const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

}} // namespace

#endif
