// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.
#include "HelloWorldService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>
#include <iostream>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::test::thrift;

class HelloWorldServiceHandler : virtual public HelloWorldServiceIf {
 public:
  HelloWorldServiceHandler() {
    // Your initialization goes here
  }

  void sayHello(std::string& _return, const std::string& username) {
    // Your implementation goes here
    printf("sayHello\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::apache::thrift::stdcxx::shared_ptr<HelloWorldServiceHandler> handler(new HelloWorldServiceHandler());
  ::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new HelloWorldServiceProcessor(handler));
  ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

//  std::shared_ptr<HelloWorldServiceHandler> handler(new HelloWorldServiceHandler());
//  std::shared_ptr<TProcessor> processor(new HelloWorldServiceProcessor(handler));
//  std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
//  std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
//  std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

